name: CI/CD Astro Deploy - Dev

on:
  push:
    branches: [ dev ]

env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRO_API_TOKEN_DEV }}
  ASTRO_WORKSPACE_ID_DEV: ${{ secrets.ASTRO_WORKSPACE_ID_DEV }}
  ASTRONOMER_DEPLOYMENT_ID_DEV: ${{ secrets.ASTRONOMER_DEPLOYMENT_ID_DEV }}
  ASTRONOMER_SKIP_PARSE:     "true"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Astro CLI
        run: |
          curl -sSL https://install.astronomer.io | sudo bash
          echo "$HOME/.astro" >> $GITHUB_PATH

      - name: List Deployments (debug)
        run: astro deployment list --workspace-id ${{ secrets.ASTRO_WORKSPACE_ID_DEV }}

      # Opción A: por ID
      - name: Deploy to Astro (dev) by ID
        run: |
          astro deploy \
            ${{ secrets.ASTRONOMER_DEPLOYMENT_ID_DEV }} \
            --workspace-id ${{ secrets.ASTRO_WORKSPACE_ID_DEV }}

      # Opción B: por nombre
      #- name: Deploy to Astro (dev) by name
      #  run: |
      #    astro deploy \
      #      -n dev \
      #      --workspace-id ${{ secrets.ASTRO_WORKSPACE_ID_DEV }}
